//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 09:17:48 AM IST 
//


package com.accenture.pota.sdk.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fileByte" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="workorderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *          &lt;element name="allocationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *          &lt;element name="workorderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resultCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resultDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileByte",
    "workorderName",
    "workorderId",
    "allocationId",
    "resultCode",
    "resultDescription"
})
@XmlRootElement(name = "RetrieveWorkorderResponse")
public class RetrieveWorkorderResponse {

	 @XmlElement(required = true)
	 protected String resultCode;
	 @XmlElement(required = true)
	 protected String resultDescription;
	 @XmlElement(required = true)
	 protected String workorderName;
	 @XmlElement(required = true)
	 protected String workorderId;
	 @XmlElement(required = true)
	 protected String allocationId;
     @XmlElement(required = true)
     protected byte[] fileByte;
  


    /**
     * Gets the value of the fileByte property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFileByte() {
        return fileByte;
    }

    /**
     * Sets the value of the fileByte property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFileByte(byte[] value) {
        this.fileByte = value;
    }

    /**
     * Gets the value of the workorderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkorderName() {
        return workorderName;
    }

    /**
     * Sets the value of the workorderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkorderName(String value) {
        this.workorderName = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultDescription() {
        return resultDescription;
    }

    /**
     * Sets the value of the resultDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultDescription(String value) {
        this.resultDescription = value;
    }
    /**
     * Gets the value of the workorderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkorderId() {
        return workorderId;
    }

    /**
     * Sets the value of the workorderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkorderId(String workorderId) {
        this.workorderId = workorderId;
    }
    
    /**
     * Gets the value of the allocationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllocationId() {
        return allocationId;
    }

    /**
     * Sets the value of the allocationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllocationId(String allocationId) {
        this.allocationId = allocationId;
    }

}
