//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.07 at 07:17:20 PM IST 
//


package com.accenture.tag.file.upload.bean;



public class WorkorderList {

    private String workorderId;
    private String allocationId;
    private String workorderName;
    private String statusId;
    private String deviceName;

    /**
     * Gets the value of the workorderId property.
     * 
     * @return
     *     possible object is
     *     
     */
    public String getWorkorderId() {
        return workorderId;
    }

    /**
     * Sets the value of the workorderId property.
     * 
     * @param value
     *     allowed object is
     *     
     */
    public void setWorkorderId(String value) {
        this.workorderId = value;
    }

    /**
     * Gets the value of the allocationId property.
     * 
     * @return
     *     possible object is
     *     
     */
    public String getAllocationId() {
        return allocationId;
    }

    /**
     * Sets the value of the allocationId property.
     * 
     * @param value
     *     allowed object is
     *     
     */
    public void setAllocationId(String value) {
        this.allocationId = value;
    }

    /**
     * Gets the value of the workorderName property.
     * 
     * @return
     *     possible object is
     *     
     */
    public String getWorkorderName() {
        return workorderName;
    }

    /**
     * Sets the value of the workorderName property.
     * 
     * @param value
     *     allowed object is
     *     
     */
    public void setWorkorderName(String value) {
        this.workorderName = value;
    }

    /**
     * Gets the value of the statusId property.
     * 
     * @return
     *     possible object is
     *     
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * Sets the value of the statusId property.
     * 
     * @param value
     *     allowed object is
     *     
     */
    public void setStatusId(String value) {
        this.statusId = value;
    }

    /**
     * Gets the value of the deviceName property.
     * 
     * @return
     *     possible object is
     *     
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * Sets the value of the deviceName property.
     * 
     * @param value
     *     allowed object is
     *     
     */
    public void setDeviceName(String value) {
        this.deviceName = value;
    }

}
